/* Autogenerated by png2wx.pl on Tue Jan 31 17:45:34 2017 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_vdrplus_pi;

#endif /* ICONS_H */
