/* Autogenerated by png2wx.pl on Tue Jan 31 17:24:39 2017 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_vdrplus;

#endif /* ICONS_H */
